---
id: Log
name: Log
full: Logging library
description: A logging library with configurable handlers, filters, and formatting.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Log
authors:
  -
    name: Mike Naberezny
    user: mnaberez
    email: mike@maintainable.com
    active: false
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  -
    name: Ralf Lang
    user: lang
    email: lang@b1-systems.de
    active: true
    role: maintainer
version:
  release: 3.0.0alpha6
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      php-extended/polyfill-php80-stringable: ^1
      psr/log: ^1
      horde/constraint: ^3
      horde/exception: ^3
      horde/util: ^3
  dev:
    composer:
      horde/test: ^3
      horde/cli: ^3
      horde/scribe: ^3
  optional:
    composer:
      horde/cli: ^3
      horde/scribe: ^3
      horde/test: ^3
    ext:
      dom: '*'
