---
id: Log
name: Log
full: Logging library
description: Horde Logging package with configurable handlers, filters, and formatting.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Log
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: true
    role: lead
  -
    name: Mike Naberezny
    user: mnaberez
    email: mike@maintainable.com
    active: true
    role: lead
version:
  release: 2.3.1
  api: 1.3.0
state:
  release: stable
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Constraint: ^2
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Util: ^2
  optional:
    pear:
      pear.horde.org/Horde_Cli: ^2
      pear.horde.org/Horde_Scribe: ^2
      pear.horde.org/Horde_Test: ^2.1
    ext:
      dom: '*'
